#!/usr/bin/env python3
"""AutoHarness starter — AgenticOS

This agent assists with code generation, review, and refactoring.

Generated by `autoharness init`.
"""

from autoharness import Constitution, ToolGovernancePipeline
from autoharness.core.types import ToolCall

# pip install anthropic openai
# import anthropic
# import openai


def main() -> None:
    # Load the constitution (auto-discovers constitution.yaml)
    constitution = Constitution.discover()
    pipeline = ToolGovernancePipeline(constitution)

    # anthropic_client = anthropic.Anthropic()
# openai_client = openai.OpenAI()

    # Example: evaluate a tool call through the governance pipeline
    call = ToolCall(
        tool_name="Bash",
        tool_input={"command": "echo Hello from AgenticOS"},
    )

    result = pipeline.process(call)
    print(f"Status: {result.status}")
    print(f"Output: {result.output}")


if __name__ == "__main__":
    main()
